name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Generates the snake GIF and SVG  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: HowardKiat
          # These next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # Push the changes to the 'output' branch
      - name: Push changes to output branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Change this to 'output' to push to the correct branch
          force: true

      # Deploy to GitHub Pages (using the 'output' branch)
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # The output branch where the files are generated
          build_dir: dist  # The directory containing the generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
